import type {
  Booking,
  Cliente,
  ConfiguracionSitio,
  Evento,
  Ingreso,
  Modelo,
  Paquete,
  SolicitudRegistro,
  UsuarioStaff,
} from "./types";

// Datos de demostración para el backoffice. En producción, todo esto vive
// detrás de la API central (ver lib/data.ts) — nada aquí toca una base de datos.

export const AGENCY_ID = "ag_default";

// Credencial de demo mientras no hay backend de auth real con hashing/DB de staff.
// El día que exista API de auth, loginAction (lib/actions.ts) es lo único que cambia.
export const CREDENCIAL_DEMO_STAFF = {
  correo: "ing.johanngut@gmail.com",
  password: "musa2026",
};

export const modelos: Modelo[] = [
  {
    id: "mdl_01",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0001",
    nombreArtistico: "Valentina Cruz",
    nombreLegal: "Valentina Cruz Espinoza",
    fechaNacimiento: "1999-03-14",
    genero: "femenino",
    nacionalidad: "Mexicana",
    contacto: { correo: "valentina.cruz@mail.com", telefono: "+52 55 1234 0001", ubicacion: "Ciudad de México" },
    fisico: { estaturaCm: 176, medidas: "84-61-90", tallas: "S", colorCabello: "Castaño", colorOjos: "Café", tonoPiel: "Trigueño" },
    categoria: "moda",
    etiquetas: ["pasarela", "editorial", "alta costura"],
    nivelExperiencia: "experimentado",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: true,
    publicoEnLanding: true,
    disponibilidad: "disponible",
    tarifaBase: 18000,
    consentimiento: { aceptado: true, fecha: "2024-01-10", versionDocumento: "v2", alcance: "Foto y video, uso comercial" },
    creadoEn: "2024-01-10",
  },
  {
    id: "mdl_02",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0002",
    nombreArtistico: "Mateo Lombardi",
    nombreLegal: "Mateo Lombardi Soto",
    fechaNacimiento: "1997-07-22",
    genero: "masculino",
    nacionalidad: "Argentina",
    contacto: { correo: "mateo.lombardi@mail.com", telefono: "+52 55 1234 0002", ubicacion: "Guadalajara" },
    fisico: { estaturaCm: 188, colorCabello: "Negro", colorOjos: "Café", tonoPiel: "Claro" },
    categoria: "comercial",
    etiquetas: ["catálogo", "fitness"],
    nivelExperiencia: "intermedio",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: false,
    publicoEnLanding: true,
    disponibilidad: "disponible",
    tarifaBase: 9500,
    consentimiento: { aceptado: true, fecha: "2024-02-02", versionDocumento: "v2", alcance: "Foto, uso comercial" },
    creadoEn: "2024-02-02",
  },
  {
    id: "mdl_03",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0003",
    nombreArtistico: "Sofía Reyes",
    nombreLegal: "Sofía Reyes Marván",
    fechaNacimiento: "2002-11-05",
    genero: "femenino",
    nacionalidad: "Mexicana",
    contacto: { correo: "sofia.reyes@mail.com", telefono: "+52 55 1234 0003", ubicacion: "Monterrey" },
    fisico: { estaturaCm: 172, medidas: "82-60-88", tallas: "XS" },
    categoria: "editorial",
    etiquetas: ["beauty", "editorial"],
    nivelExperiencia: "intermedio",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: true,
    publicoEnLanding: true,
    disponibilidad: "ocupado",
    tarifaBase: 12000,
    consentimiento: { aceptado: true, fecha: "2024-03-18", versionDocumento: "v2", alcance: "Foto y video" },
    creadoEn: "2024-03-18",
  },
  {
    id: "mdl_04",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0004",
    nombreArtistico: "Diego Marín",
    nombreLegal: "Diego Marín Ortega",
    fechaNacimiento: "2000-05-30",
    genero: "masculino",
    nacionalidad: "Colombiana",
    contacto: { correo: "diego.marin@mail.com", telefono: "+52 55 1234 0004", ubicacion: "Ciudad de México" },
    categoria: "fitness",
    etiquetas: ["fitness", "deportivo"],
    nivelExperiencia: "nuevo",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "borrador",
    destacado: false,
    publicoEnLanding: false,
    disponibilidad: "disponible",
    tarifaBase: 7000,
    creadoEn: "2025-09-01",
  },
  {
    id: "mdl_05",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0005",
    nombreArtistico: "Camila Duarte",
    nombreLegal: "Camila Duarte Pinto",
    fechaNacimiento: "1998-09-12",
    genero: "femenino",
    nacionalidad: "Brasileña",
    contacto: { correo: "camila.duarte@mail.com", telefono: "+52 55 1234 0005", ubicacion: "Ciudad de México" },
    fisico: { estaturaCm: 178, medidas: "85-62-91" },
    categoria: "moda",
    etiquetas: ["pasarela", "lujo"],
    nivelExperiencia: "experimentado",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: true,
    publicoEnLanding: true,
    disponibilidad: "disponible",
    tarifaBase: 21000,
    consentimiento: { aceptado: true, fecha: "2023-11-20", versionDocumento: "v1", alcance: "Foto y video, uso comercial" },
    creadoEn: "2023-11-20",
  },
  {
    id: "mdl_06",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0006",
    nombreArtistico: "Renata Solís",
    nombreLegal: "Renata Solís Aguirre",
    fechaNacimiento: "2003-01-27",
    genero: "femenino",
    nacionalidad: "Mexicana",
    contacto: { correo: "renata.solis@mail.com", telefono: "+52 55 1234 0006", ubicacion: "Puebla" },
    categoria: "influencer",
    etiquetas: ["redes sociales", "lifestyle"],
    nivelExperiencia: "nuevo",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: false,
    publicoEnLanding: false,
    disponibilidad: "disponible",
    tarifaBase: 6500,
    creadoEn: "2025-06-15",
  },
  {
    id: "mdl_07",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0007",
    nombreArtistico: "Joaquín Vidal",
    nombreLegal: "Joaquín Vidal Núñez",
    fechaNacimiento: "1995-12-08",
    genero: "masculino",
    nacionalidad: "Chilena",
    contacto: { correo: "joaquin.vidal@mail.com", telefono: "+52 55 1234 0007", ubicacion: "Ciudad de México" },
    categoria: "comercial",
    etiquetas: ["catálogo", "ejecutivo"],
    nivelExperiencia: "experimentado",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "inactivo",
    destacado: false,
    publicoEnLanding: false,
    disponibilidad: "no disponible",
    tarifaBase: 8500,
    notasInternas: "Pausa temporal por agenda personal, retoma en Q3.",
    creadoEn: "2022-04-11",
  },
  {
    id: "mdl_08",
    agencyId: AGENCY_ID,
    numeroModelo: "MOD-0008",
    nombreArtistico: "Isabela Hoyos",
    nombreLegal: "Isabela Hoyos Restrepo",
    fechaNacimiento: "2001-08-19",
    genero: "femenino",
    nacionalidad: "Colombiana",
    contacto: { correo: "isabela.hoyos@mail.com", telefono: "+52 55 1234 0008", ubicacion: "Querétaro" },
    fisico: { estaturaCm: 174, medidas: "83-60-89" },
    categoria: "promocional",
    etiquetas: ["activaciones", "stands"],
    nivelExperiencia: "intermedio",
    mainPhotoUrl: "",
    bookUrls: [],
    estado: "activo",
    destacado: false,
    publicoEnLanding: true,
    disponibilidad: "disponible",
    tarifaBase: 5500,
    consentimiento: { aceptado: true, fecha: "2024-07-02", versionDocumento: "v2", alcance: "Foto, uso comercial" },
    creadoEn: "2024-07-02",
  },
];

export const solicitudesRegistro: SolicitudRegistro[] = [
  {
    id: "sol_01",
    agencyId: AGENCY_ID,
    nombreCompleto: "Lucía Fernández Ríos",
    correo: "lucia.fernandez@mail.com",
    telefono: "+52 55 9876 0001",
    fechaNacimiento: "2004-02-10",
    genero: "femenino",
    nacionalidad: "Mexicana",
    ubicacion: "Ciudad de México",
    categoria: "moda",
    fotoUrl: "",
    estado: "pendiente",
    enviadoEn: "2026-06-20",
    actualizadoEn: "2026-06-20",
    tokenRevision: "tok_a1b2c3",
  },
  {
    id: "sol_02",
    agencyId: AGENCY_ID,
    nombreCompleto: "Bruno Albanesi",
    correo: "bruno.albanesi@mail.com",
    telefono: "+52 55 9876 0002",
    fechaNacimiento: "1999-10-02",
    genero: "masculino",
    nacionalidad: "Argentina",
    ubicacion: "Ciudad de México",
    categoria: "fitness",
    fotoUrl: "",
    estado: "pendiente",
    enviadoEn: "2026-06-21",
    actualizadoEn: "2026-06-21",
    tokenRevision: "tok_d4e5f6",
  },
  {
    id: "sol_03",
    agencyId: AGENCY_ID,
    nombreCompleto: "Paula Méndez",
    correo: "paula.mendez@mail.com",
    telefono: "+52 55 9876 0003",
    fechaNacimiento: "2003-05-17",
    genero: "femenino",
    nacionalidad: "Mexicana",
    ubicacion: "Guadalajara",
    categoria: "editorial",
    fotoUrl: "",
    estado: "requiere_cambios",
    notaInterna: "Falta verificar identidad con el documento oficial.",
    retroParaModelo: "¡Gracias por tu interés! Necesitamos que subas fotos sin filtro y con mejor iluminación natural para evaluar tu book.",
    enviadoEn: "2026-06-15",
    actualizadoEn: "2026-06-18",
    tokenRevision: "tok_g7h8i9",
  },
  {
    id: "sol_04",
    agencyId: AGENCY_ID,
    nombreCompleto: "Tomás Ibarra",
    correo: "tomas.ibarra@mail.com",
    telefono: "+52 55 9876 0004",
    fechaNacimiento: "1998-08-29",
    genero: "masculino",
    nacionalidad: "Mexicana",
    ubicacion: "Monterrey",
    categoria: "comercial",
    fotoUrl: "",
    estado: "aprobado",
    notaInterna: "Buen book, aprobado sin observaciones.",
    retroParaModelo: "¡Bienvenido a la agencia! Pronto te contactaremos para tu primer casting.",
    enviadoEn: "2026-06-02",
    actualizadoEn: "2026-06-05",
    tokenRevision: "tok_j1k2l3",
  },
  {
    id: "sol_05",
    agencyId: AGENCY_ID,
    nombreCompleto: "Daniela Soto",
    correo: "daniela.soto@mail.com",
    telefono: "+52 55 9876 0005",
    fechaNacimiento: "2005-01-09",
    genero: "femenino",
    nacionalidad: "Mexicana",
    ubicacion: "Puebla",
    categoria: "influencer",
    fotoUrl: "",
    estado: "rechazado",
    notaInterna: "Perfil no encaja con las categorías activas de la agencia.",
    retroParaModelo: "Gracias por tu interés. En este momento no encontramos un encaje con las categorías que manejamos.",
    enviadoEn: "2026-05-28",
    actualizadoEn: "2026-06-01",
    tokenRevision: "tok_m4n5o6",
    rechazadoEn: "2026-06-01",
  },
];

export const clientes: Cliente[] = [
  { id: "cli_01", agencyId: AGENCY_ID, empresa: "Vogue Studio MX", contactoNombre: "Renata Aguilar", correo: "renata@voguestudio.mx", telefono: "+52 55 2000 0001", industria: "Moda", eventosTotales: 6, ingresosTotales: 312000, creadoEn: "2023-02-10" },
  { id: "cli_02", agencyId: AGENCY_ID, empresa: "Lumière Cosméticos", contactoNombre: "Hugo Beltrán", correo: "hugo@lumiere.com", telefono: "+52 55 2000 0002", industria: "Belleza", eventosTotales: 4, ingresosTotales: 198000, creadoEn: "2023-06-22" },
  { id: "cli_03", agencyId: AGENCY_ID, empresa: "Aurora Retail Group", contactoNombre: "Marcela Tovar", correo: "marcela@auroraretail.com", telefono: "+52 55 2000 0003", industria: "Retail", eventosTotales: 3, ingresosTotales: 145000, creadoEn: "2024-01-15" },
  { id: "cli_04", agencyId: AGENCY_ID, empresa: "Nova Sportswear", contactoNombre: "Iván Cordero", correo: "ivan@novasport.com", telefono: "+52 55 2000 0004", industria: "Deportes", eventosTotales: 2, ingresosTotales: 86000, creadoEn: "2024-08-09" },
  { id: "cli_05", agencyId: AGENCY_ID, empresa: "Cantera Joyería", contactoNombre: "Ximena Paredes", correo: "ximena@canterajoyeria.com", telefono: "+52 55 2000 0005", industria: "Joyería", eventosTotales: 1, ingresosTotales: 40000, creadoEn: "2025-03-30" },
];

export const eventos: Evento[] = [
  { id: "evt_01", agencyId: AGENCY_ID, nombre: "Campaña Primavera 2026", clienteId: "cli_01", tipo: "Editorial", lugar: "Estudio Polanco, CDMX", fechaInicio: "2026-06-28", fechaFin: "2026-06-28", estado: "confirmado", bookingsIds: ["bkg_01", "bkg_02"] },
  { id: "evt_02", agencyId: AGENCY_ID, nombre: "Lanzamiento línea Glow", clienteId: "cli_02", tipo: "Activación", lugar: "Centro Histórico, CDMX", fechaInicio: "2026-07-03", fechaFin: "2026-07-03", estado: "planeado", bookingsIds: ["bkg_03"] },
  { id: "evt_03", agencyId: AGENCY_ID, nombre: "Catálogo Otoño Aurora", clienteId: "cli_03", tipo: "Catálogo", lugar: "Foro Santa Fe, CDMX", fechaInicio: "2026-07-10", fechaFin: "2026-07-11", estado: "planeado", bookingsIds: ["bkg_04", "bkg_05"] },
  { id: "evt_04", agencyId: AGENCY_ID, nombre: "Sesión Nova Run", clienteId: "cli_04", tipo: "Comercial", lugar: "Bosque de Chapultepec, CDMX", fechaInicio: "2026-06-15", fechaFin: "2026-06-15", estado: "finalizado", bookingsIds: ["bkg_06"] },
  { id: "evt_05", agencyId: AGENCY_ID, nombre: "Pasarela Joyería Cantera", clienteId: "cli_05", tipo: "Pasarela", lugar: "Hotel St. Regis, CDMX", fechaInicio: "2026-05-30", fechaFin: "2026-05-30", estado: "finalizado", bookingsIds: ["bkg_07", "bkg_08"] },
  { id: "evt_06", agencyId: AGENCY_ID, nombre: "Backstage Vogue Studio", clienteId: "cli_01", tipo: "Editorial", lugar: "Estudio Roma Norte, CDMX", fechaInicio: "2026-06-05", fechaFin: "2026-06-05", estado: "cancelado", bookingsIds: [] },
];

export const bookings: Booking[] = [
  { id: "bkg_01", agencyId: AGENCY_ID, eventoId: "evt_01", modeloId: "mdl_01", tarifa: 18000, estado: "confirmado", fecha: "2026-06-28" },
  { id: "bkg_02", agencyId: AGENCY_ID, eventoId: "evt_01", modeloId: "mdl_05", tarifa: 21000, estado: "confirmado", fecha: "2026-06-28" },
  { id: "bkg_03", agencyId: AGENCY_ID, eventoId: "evt_02", modeloId: "mdl_03", tarifa: 12000, estado: "pendiente", fecha: "2026-07-03" },
  { id: "bkg_04", agencyId: AGENCY_ID, eventoId: "evt_03", modeloId: "mdl_02", tarifa: 9500, estado: "pendiente", fecha: "2026-07-10" },
  { id: "bkg_05", agencyId: AGENCY_ID, eventoId: "evt_03", modeloId: "mdl_08", tarifa: 5500, estado: "pendiente", fecha: "2026-07-10" },
  { id: "bkg_06", agencyId: AGENCY_ID, eventoId: "evt_04", modeloId: "mdl_04", tarifa: 7000, estado: "completado", fecha: "2026-06-15" },
  { id: "bkg_07", agencyId: AGENCY_ID, eventoId: "evt_05", modeloId: "mdl_01", tarifa: 18000, estado: "completado", fecha: "2026-05-30" },
  { id: "bkg_08", agencyId: AGENCY_ID, eventoId: "evt_05", modeloId: "mdl_06", tarifa: 6500, estado: "completado", fecha: "2026-05-30" },
  { id: "bkg_09", agencyId: AGENCY_ID, eventoId: "evt_06", modeloId: "mdl_07", tarifa: 8500, estado: "cancelado", fecha: "2026-06-05" },
];

export const paquetes: Paquete[] = [
  { id: "pkg_01", agencyId: AGENCY_ID, nombre: "Propuesta Primavera — Vogue Studio", clienteId: "cli_01", modeloIds: ["mdl_01", "mdl_05", "mdl_03"], estado: "aprobado", total: 51000, creadoEn: "2026-06-10" },
  { id: "pkg_02", agencyId: AGENCY_ID, nombre: "Glow Launch — Lumière", clienteId: "cli_02", modeloIds: ["mdl_03", "mdl_06"], estado: "enviado", total: 18500, creadoEn: "2026-06-18" },
  { id: "pkg_03", agencyId: AGENCY_ID, nombre: "Catálogo Otoño — Aurora Retail", clienteId: "cli_03", modeloIds: ["mdl_02", "mdl_08"], estado: "enviado", total: 15000, creadoEn: "2026-06-19" },
  { id: "pkg_04", agencyId: AGENCY_ID, nombre: "Nova Run 2026", clienteId: "cli_04", modeloIds: ["mdl_04", "mdl_02"], estado: "borrador", total: 16500, creadoEn: "2026-06-21" },
  { id: "pkg_05", agencyId: AGENCY_ID, nombre: "Joyería Cantera — Capsula", clienteId: "cli_05", modeloIds: ["mdl_01"], estado: "rechazado", total: 18000, creadoEn: "2026-05-12" },
];

export const ingresos: Ingreso[] = [
  { id: "ing_01", agencyId: AGENCY_ID, eventoId: "evt_04", clienteId: "cli_04", monto: 7000, metodo: "transferencia", fecha: "2026-06-16" },
  { id: "ing_02", agencyId: AGENCY_ID, eventoId: "evt_05", clienteId: "cli_05", monto: 24500, metodo: "transferencia", fecha: "2026-05-31" },
  { id: "ing_03", agencyId: AGENCY_ID, eventoId: "evt_05", clienteId: "cli_05", monto: 15500, metodo: "tarjeta", fecha: "2026-06-02" },
  { id: "ing_04", agencyId: AGENCY_ID, eventoId: "evt_01", clienteId: "cli_01", monto: 39000, metodo: "transferencia", fecha: "2026-06-22" },
];

// Serie mensual para el gráfico de ingresos (últimos 6 meses).
export const ingresosPorMes = [
  { mes: "Ene", total: 64000 },
  { mes: "Feb", total: 78500 },
  { mes: "Mar", total: 91000 },
  { mes: "Abr", total: 73200 },
  { mes: "May", total: 102500 },
  { mes: "Jun", total: 86000 },
];

export const configuracionSitio: ConfiguracionSitio = {
  agencyId: AGENCY_ID,
  nombreAgencia: "GlamourModels",
  logoUrl: "",
  colorPrimario: "#BA1B5D",
  heroTitulo: "Talento que define la temporada",
  heroSubtitulo: "Representamos modelos y talento para marcas que buscan presencia, carácter y consistencia.",
  registroPublicoActivo: true,
  registroLinkSlug: "registro-glamour-2026",
};
